Repository codesquad-member-2020/todo-10, pull requests merged in 2020-04, with the labels that each got.

#4 [#3] chore: 루트 디렉토리 .gitignore 파일 추가
  .gitignore
Labels: Team

#12 Feature fe/issue 2
  FE/babel.config.js
  FE/package.json
  FE/src/index.html
  FE/src/js/main.js
  FE/src/style/button.css
  FE/src/style/button.scss
  FE/src/style/card.css
  FE/src/style/card.scss
  FE/src/style/common.css
  FE/src/style/common.scss
  FE/src/style/layout.scss
  FE/src/style/menu.css
  FE/src/style/menu.scss
  FE/src/style/mixin.scss
  FE/src/style/reset.scss
  FE/src/style/todo.css
  FE/src/style/todo.scss
  FE/src/style/var.css
  FE/src/style/var.scss
  FE/webpack.config.js
Labels: FE

#13 [#2]chore: webpack 자동화
  FE/package.json
Labels: FE

#18 [#10] docs: README.md 수정
  README.md
Labels: BE

#20 [#19] refactor: Mockup Api 로그인 요청 시, 응답 객체 오류 수정
  BE/src/main/java/com/codesquad/team10/todo/api/MockTodoApiController.java
  README.md
Labels: BE

#21 로그인 Mockup API 수정 배포
  BE/src/main/java/com/codesquad/team10/todo/api/MockTodoApiController.java
  README.md
Labels: BE, deploy

#22 [iOS][issue-1] 전체적으로 기본적인 뷰 구성을 하고 풀리퀘스트합니다.
  iOS/.gitignore
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/Todo/Todo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Todo/Todo/AppDelegate.swift
  iOS/Todo/Todo/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Todo/Todo/Assets.xcassets/Contents.json
  iOS/Todo/Todo/Base.lproj/LaunchScreen.storyboard
  iOS/Todo/Todo/Base.lproj/Main.storyboard
  iOS/Todo/Todo/Delegates/CardListTableDelegate.swift
  iOS/Todo/Todo/Info.plist
  iOS/Todo/Todo/Models/CardListTableDataSource.swift
  iOS/Todo/Todo/SceneDelegate.swift
  iOS/Todo/Todo/ViewControllers/AcitivitiyLogController.swift
  iOS/Todo/Todo/ViewControllers/CardListController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/Views/CardCell.swift
  iOS/Todo/Todo/Views/CardListScrollView.swift
  iOS/Todo/Todo/Views/CardListTable.swift
  iOS/Todo/Todo/Views/ReusableView.swift
  iOS/Todo/Todo/Views/TitleView.swift
  iOS/Todo/TodoTests/Info.plist
  iOS/Todo/TodoTests/TodoTests.swift
  iOS/Todo/TodoUITests/Info.plist
  iOS/Todo/TodoUITests/TodoUITests.swift
Labels: iOS

#35 [FE] 분업을 위한 베이스
  FE/src/index.html
  FE/src/js/eventHandles/card.js
  FE/src/js/eventHandles/column.js
  FE/src/js/eventHandles/form.js
  FE/src/js/todoEventManager.js
  FE/src/js/todoView.js
  FE/src/js/util/commonUtil.js
  FE/src/style/button.css
  FE/src/style/card.css
  FE/src/style/common.css
  FE/src/style/menu.css
  FE/src/style/todo.css
  FE/src/style/var.css
  FE/src/ts/eventHandles/card.ts
  FE/src/ts/eventHandles/column.ts
  FE/src/ts/eventHandles/form.ts
  FE/src/ts/todoEventManager.ts
  FE/src/ts/todoView.ts
  FE/src/ts/util/commonUtil.ts
Labels: FE

#38 [FE] form button attribute modify
  FE/src/js/todoView.js
  FE/src/ts/todoView.ts
Labels: FE

#39 [iOS][#24] 서버로부터 데이터를 로드하여 Codable객체로 처리하는 것을 성공하였습니다.
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo/Coder/CardListsUseCase.swift
  iOS/Todo/Todo/Info.plist
  iOS/Todo/Todo/JsonData/JsonData.swift
  iOS/Todo/Todo/Models/Response.swift
  iOS/Todo/Todo/Network/NetworkManager.swift
  iOS/Todo/Todo/ViewControllers/CardListController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/Views/CardCell.swift
Labels: iOS

#47 [BE][#46] feat: Cors 방지 설정 추가
  BE/src/main/java/com/codesquad/team10/todo/config/CorsConfig.java
Labels: BE, bug

#52 Cors 설정 추가 2차 배포
  BE/.idea/dataSources.xml
  BE/build.gradle
  BE/src/main/java/com/codesquad/team10/todo/config/CorsConfig.java
  BE/src/main/resources/application-local.properties
  BE/src/main/resources/application-master.properties
  BE/src/main/resources/application.properties
  FE/src/js/eventHandles/form.js
  FE/src/js/todoEventManager.js
  FE/src/js/util/commonUtil.js
  FE/src/style/button.scss
  FE/src/style/todo.scss
  FE/src/ts/eventHandles/form.ts
  FE/src/ts/todoEventManager.ts
  FE/src/ts/util/commonUtil.ts
Labels: BE, deploy

#55 [FE] 0409 작업본 머지
  FE/package.json
  FE/src/js/_data/mockdata.js
  FE/src/js/eventHandles/card.js
  FE/src/js/todoEventManager.js
  FE/src/js/todoModel.js
  FE/src/js/todoView.js
  FE/src/ts/_data/mockdata.ts
  FE/src/ts/eventHandles/card.ts
  FE/src/ts/todoEventManager.ts
  FE/src/ts/todoModel.ts
  FE/src/ts/todoView.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: FE

#59 [FE] 함수 이름 리팩토링
  FE/src/index.html
  FE/src/ts/eventHandles/card.ts
  FE/src/ts/eventHandles/column.ts
  FE/src/ts/eventHandles/form.ts
  FE/src/ts/todoEventManager.ts
  FE/src/ts/todoModel.ts
  FE/src/ts/todoView.ts
  FE/src/ts/util/commonUtil.ts
Labels: FE

#60 [iOS][#58] JK의 피드백을 반영하여 풀리퀘스트 보냅니다.
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo/Coder/CardListsUseCase.swift
  iOS/Todo/Todo/JsonData/StubJsonData.swift
  iOS/Todo/Todo/Models/CardListTableDataSource.swift
  iOS/Todo/Todo/Models/CardLists.swift
  iOS/Todo/Todo/Models/Response.swift
  iOS/Todo/Todo/Network/NetworkManager.swift
  iOS/Todo/Todo/ViewControllers/CardListViewController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/ViewModels/CardViewModel.swift
  iOS/Todo/Todo/ViewModels/CardViewModels.swift
  iOS/Todo/Todo/ViewModels/TitleViewModel.swift
  iOS/Todo/Todo/ViewModels/ViewModelBinding.swift
Labels: iOS

#63 [BE][#62] refactor: 카드 삭제 시 응답 데이터 수정
  BE/src/main/java/com/codesquad/team10/todo/api/mock/MockCardApiController.java
  BE/src/main/java/com/codesquad/team10/todo/service/CardServiceImpl.java
Labels: BE, enhancement

#64 카드 삭제 시 응답 데이터 변경 배포
  BE/src/main/java/com/codesquad/team10/todo/api/mock/MockCardApiController.java
  BE/src/main/java/com/codesquad/team10/todo/service/CardServiceImpl.java
  FE/.gitignore
  FE/package.json
  FE/src/index.html
  FE/src/js/_data/mockdata.js
  FE/src/js/contants/constant.js
  FE/src/js/contants/url.js
  FE/src/js/eventHandles/card.js
  FE/src/js/eventHandles/column.js
  FE/src/js/eventHandles/form.js
  FE/src/js/main.js
  FE/src/js/todoController.js
  FE/src/js/todoEventManager.js
  FE/src/js/todoModel.js
  FE/src/js/todoView.js
  FE/src/js/util/commonUtil.js
  FE/src/ts/_data/mockdata.ts
  FE/src/ts/eventHandles/card.ts
  FE/src/ts/eventHandles/column.ts
  FE/src/ts/eventHandles/form.ts
  FE/src/ts/todoEventManager.ts
  FE/src/ts/todoModel.ts
  FE/src/ts/todoView.ts
  FE/src/ts/util/commonUtil.ts
  FE/tsconfig.json
  FE/webpack.config.js
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo/Coder/CardListsUseCase.swift
  iOS/Todo/Todo/JsonData/StubJsonData.swift
  iOS/Todo/Todo/Models/CardListTableDataSource.swift
  iOS/Todo/Todo/Models/CardLists.swift
  iOS/Todo/Todo/Models/Response.swift
  iOS/Todo/Todo/Network/NetworkManager.swift
  iOS/Todo/Todo/ViewControllers/CardListViewController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/ViewModels/CardViewModel.swift
  iOS/Todo/Todo/ViewModels/CardViewModels.swift
  iOS/Todo/Todo/ViewModels/TitleViewModel.swift
  iOS/Todo/Todo/ViewModels/ViewModelBinding.swift
Labels: BE, enhancement

#73 [iOS][#41] 해당 행을 왼쪽으로 끌어 삭제 버튼을 누르면 해당 행이 삭제 되도록 기능 구현하였습니다.
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo/Coder/CardListsUseCase.swift
  iOS/Todo/Todo/Coder/DeleteUseCase.swift
  iOS/Todo/Todo/Delegates/CardListTableDelegate.swift
  iOS/Todo/Todo/JsonData/StubJsonData.swift
  iOS/Todo/Todo/Models/Card.swift
  iOS/Todo/Todo/Models/CardListTableDataSource.swift
  iOS/Todo/Todo/Models/CardResponse.swift
  iOS/Todo/Todo/Models/Response.swift
  iOS/Todo/Todo/Models/Status.swift
  iOS/Todo/Todo/Network/NetworkManager.swift
  iOS/Todo/Todo/Utils/ButtonData.swift
  iOS/Todo/Todo/Utils/StubJsonData.swift
  iOS/Todo/Todo/ViewControllers/CardListViewController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/ViewModels/CardViewModel.swift
  iOS/Todo/Todo/Views/CardListScrollView.swift
Labels: enhancement, iOS

#75 [BE][#74] 카드 수정 시 응답 데이터 변경
  BE/src/main/java/com/codesquad/team10/todo/api/mock/MockCardApiController.java
  BE/src/main/java/com/codesquad/team10/todo/domain/Card.java
  BE/src/main/java/com/codesquad/team10/todo/domain/Section.java
  BE/src/main/java/com/codesquad/team10/todo/domain/User.java
Labels: BE, enhancement

#78 [FE] 드래그 앤 드랍 기능 구현
  FE/src/style/common.scss
  FE/src/style/drag.scss
  FE/src/ts/eventHandles/card.ts
  FE/src/ts/todoEventManager.ts
Labels: FE

#79 [FE] 드래그 버그 픽스 PR
  FE/src/ts/eventHandles/card.ts
Labels: FE

#81 [iOS][#57] 카드를 길게 클릭하면 메뉴(이동,편집,삭제)가 나오도록하고 삭제만 기능 구현하였습니다.
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo.xcodeproj/xcshareddata/xcschemes/Todo.xcscheme
  iOS/Todo/Todo/Coder/CardListsUseCase.swift
  iOS/Todo/Todo/Coder/DeleteUseCase.swift
  iOS/Todo/Todo/Delegates/CardListTableDelegate.swift
  iOS/Todo/Todo/Models/CardListsResponse.swift
  iOS/Todo/Todo/Models/CardResponse.swift
  iOS/Todo/Todo/Network/NetworkManager.swift
  iOS/Todo/Todo/Utils/StubJsonData.swift
  iOS/Todo/Todo/ViewModels/CardViewModel.swift
Labels: iOS

#82 [FE] 카드 추가 시 드래그 안되던 버그 픽스
  FE/src/ts/_data/mockdata.ts
  FE/src/ts/todoEventManager.ts
  FE/src/ts/todoView.ts
Labels: FE, bug

#84 [FE] 프로젝트 중간 리팩토링
  FE/package.json
  FE/src/index.html
  FE/src/style/drag.scss
  FE/src/ts/contants/constant.ts
  FE/src/ts/contants/url.ts
  FE/src/ts/eventHandles/card.ts
  FE/src/ts/eventHandles/column.ts
  FE/src/ts/eventHandles/form.ts
  FE/src/ts/eventHandles/modal.ts
  FE/src/ts/http/request.ts
  FE/src/ts/interface/todoInterface.ts
  FE/src/ts/main.ts
  FE/src/ts/todoController.ts
  FE/src/ts/todoEventManager.ts
  FE/src/ts/todoModel.ts
  FE/src/ts/todoModules/todoController.ts
  FE/src/ts/todoModules/todoEventManager.ts
  FE/src/ts/todoModules/todoView.ts
  FE/src/ts/todoModules/todoViewTemplate.ts
  FE/src/ts/todoView.ts
  FE/src/ts/util/commonUtil.ts
  FE/src/ts/util/todoUtil.ts
  FE/webpack.config.js
Labels: FE

#86 Feature fe/issue 83
  FE/src/style/card.scss
  FE/src/style/reset.scss
  FE/src/style/todo.scss
  FE/src/ts/eventHandles/form.ts
  FE/src/ts/eventHandles/modal.ts
  FE/src/ts/todoModules/todoEventManager.ts
  FE/src/ts/todoModules/todoView.ts
Labels: FE

#85 [iOS][#56] 추가 버튼 기능 구현하였습니다
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo/Coder/ColumnsUseCase.swift
  iOS/Todo/Todo/Coder/CreateUseCase.swift
  iOS/Todo/Todo/Coder/DeleteUseCase.swift
  iOS/Todo/Todo/Controller/Controller.swift
  iOS/Todo/Todo/Delegates/AppDelegate.swift
  iOS/Todo/Todo/Delegates/ColumnTableDelegate.swift
  iOS/Todo/Todo/Delegates/ContentViewDelegate.swift
  iOS/Todo/Todo/Delegates/SceneDelegate.swift
  iOS/Todo/Todo/Delegates/TitleFieldDelegate.swift
  iOS/Todo/Todo/Models/CardLists.swift
  iOS/Todo/Todo/Models/CardResponse.swift
  iOS/Todo/Todo/Models/ColumnTableDataSource.swift
  iOS/Todo/Todo/Models/Columns.swift
  iOS/Todo/Todo/Models/ColumnsResponse.swift
  iOS/Todo/Todo/Network/NetworkManager.swift
  iOS/Todo/Todo/Utils/StubJsonData.swift
  iOS/Todo/Todo/ViewControllers/CardListViewController.swift
  iOS/Todo/Todo/ViewControllers/CardViewController.swift
  iOS/Todo/Todo/ViewControllers/ColumnViewController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/ViewModels/ColumnViewController's/CardViewModel.swift
  iOS/Todo/Todo/ViewModels/ColumnViewController's/TitleViewModel.swift
  iOS/Todo/Todo/ViewModels/ViewModelBinding.swift
  iOS/Todo/Todo/Views/CardListScrollView.swift
  iOS/Todo/Todo/Views/CardVIewController's/CancelButton.swift
  iOS/Todo/Todo/Views/CardVIewController's/ContentView.swift
  iOS/Todo/Todo/Views/CardVIewController's/CreateButton.swift
  iOS/Todo/Todo/Views/CardVIewController's/FormatImageView.swift
  iOS/Todo/Todo/Views/CardVIewController's/TitleField.swift
  iOS/Todo/Todo/Views/ColumnViewController's/CardCell.swift
  iOS/Todo/Todo/Views/ColumnViewController's/ColumnTable.swift
  iOS/Todo/Todo/Views/ColumnViewController's/TitleView.swift
  iOS/Todo/Todo/Views/MainViewController's/ColumnScrollView.swift
  iOS/Todo/Todo/Views/MainViewController's/ColumnStackView.swift
  iOS/Todo/Todo/Views/ReusableView.swift
Labels: iOS

#97 [#94] refactor : 타입스크립트 타입 적용
  FE/src/ts/eventHandles/card.ts
  FE/src/ts/interface/todoInterface.ts
  FE/tsconfig.json
Labels: FE

#108 [iOS][#90] 카드 수정 기능을 구현하고 JK의 피드백을 반영하였습니다.
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo/Coder/ColumnsUseCase.swift
  iOS/Todo/Todo/Coder/CreateUseCase.swift
  iOS/Todo/Todo/Coder/DeleteUseCase.swift
  iOS/Todo/Todo/Coder/EditedCardViewModelUseCase.swift
  iOS/Todo/Todo/Coder/EndPointFactory.swift
  iOS/Todo/Todo/Coder/NewCardViewModelUseCase.swift
  iOS/Todo/Todo/Delegates/ColumnTableDelegate.swift
  iOS/Todo/Todo/Delegates/ContentViewDelegate.swift
  iOS/Todo/Todo/Models/ColumnTableDataSource.swift
  iOS/Todo/Todo/Models/DeleteResponse.swift
  iOS/Todo/Todo/Models/NewCard.swift
  iOS/Todo/Todo/Network/NetworkManager.swift
  iOS/Todo/Todo/Utils/ButtonData.swift
  iOS/Todo/Todo/Utils/StubJsonData.swift
  iOS/Todo/Todo/ViewControllers/CardViewController.swift
  iOS/Todo/Todo/ViewControllers/ColumnViewController.swift
  iOS/Todo/Todo/ViewControllers/EditingCardViewController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/ViewControllers/NewCardViewController.swift
  iOS/Todo/Todo/ViewModels/ColumnViewController's/TitleViewModel.swift
  iOS/Todo/Todo/Views/CardVIewController's/ContentView.swift
  iOS/Todo/Todo/Views/ColumnViewController's/TitleView.swift
Labels: enhancement, iOS, refactor

#123 [BE][#122] fix: 배포 빌드 시 테스트 제거, mysql 접속 url을 localhost로 변경
  BE/src/main/resources/application-master.properties
  BE/src/test/java/com/codesquad/team10/todo/db/DBConnection.java
Labels: BE, bug

#124 빌드 시 테스트 제거, mysql 접속 url을 localhost로 변경 배포
  BE/src/main/resources/application-master.properties
  BE/src/test/java/com/codesquad/team10/todo/db/DBConnection.java
Labels: BE, bug

#126 [iOS][#91] MoveToDone, 드래그 앤 드랍 기능 구현하였습니다.
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo/Coder/ColumnsUseCase.swift
  iOS/Todo/Todo/Coder/DeleteUseCase.swift
  iOS/Todo/Todo/Coder/EditedCardViewModelUseCase.swift
  iOS/Todo/Todo/Coder/NewCardViewModelUseCase.swift
  iOS/Todo/Todo/Models/ColumnTableDataSource.swift
  iOS/Todo/Todo/Models/NewCard.swift
  iOS/Todo/Todo/ViewControllers/ColumnViewController.swift
  iOS/Todo/Todo/ViewControllers/EditingCardViewController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/ViewControllers/NewCardViewController.swift
  iOS/Todo/TodoTests/DragObject.swift
Labels: enhancement, iOS

#127 [BE][#125] feat: 카드 삭제 soft delete로 변경
  BE/src/main/java/com/codesquad/team10/todo/api/CardController.java
  BE/src/main/java/com/codesquad/team10/todo/entity/Card.java
  BE/src/main/java/com/codesquad/team10/todo/entity/Section.java
Labels: BE

#128 카드 삭제 soft delete로 변경 배포
  BE/src/main/java/com/codesquad/team10/todo/api/CardController.java
  BE/src/main/java/com/codesquad/team10/todo/entity/Card.java
  BE/src/main/java/com/codesquad/team10/todo/entity/Section.java
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo/Coder/ColumnsUseCase.swift
  iOS/Todo/Todo/Coder/DeleteUseCase.swift
  iOS/Todo/Todo/Coder/EditedCardViewModelUseCase.swift
  iOS/Todo/Todo/Coder/NewCardViewModelUseCase.swift
  iOS/Todo/Todo/Models/ColumnTableDataSource.swift
  iOS/Todo/Todo/Models/NewCard.swift
  iOS/Todo/Todo/ViewControllers/ColumnViewController.swift
  iOS/Todo/Todo/ViewControllers/EditingCardViewController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/ViewControllers/NewCardViewController.swift
  iOS/Todo/TodoTests/DragObject.swift
Labels: BE, deploy

#132 [FE] 로그 기능 구현
  FE/.gitignore
  FE/src/index.html
  FE/src/style/common.scss
  FE/src/style/loading.scss
  FE/src/ts/contants/url.ts
  FE/src/ts/todoModules/eventHandles/card.ts
  FE/src/ts/todoModules/eventHandles/form.ts
  FE/src/ts/todoModules/eventHandles/menu.ts
  FE/src/ts/todoModules/todoController.ts
  FE/src/ts/todoModules/todoEventManager.ts
  FE/src/ts/todoModules/todoView.ts
  FE/src/ts/todoModules/todoViewTemplate.ts
  FE/src/ts/utils/commonUtil.ts
  FE/src/ts/utils/httpRequestUtil.ts
  FE/src/ts/utils/todoUtil.ts
Labels: FE

#133 [FE] 메뉴 로그에 따라 스크롤이 발생하지 않던 버그 픽스
  FE/src/style/menu.scss
Labels: FE, bug

#136 [FE] 작업 브랜치 머지 중 발생한 버그 픽스
  FE/src/index.html
  FE/src/style/loading.scss
  FE/src/ts/loginModule/data.ts
  FE/src/ts/main.ts
  FE/src/ts/todoModules/todoController.ts
  FE/src/ts/utils/httpRequestUtil.ts
Labels: FE, bug

#139 [BE][#137] fix: 이미 지워진 카드 id에 대해서 삭제 시도하는 경우, 에러 응답
  BE/src/main/java/com/codesquad/team10/todo/api/CardController.java
Labels: BE, bug

#142 Refactor: iOS/issue 141
  iOS/Todo/Todo/Models/CardListTableDataSource.swift
  iOS/Todo/Todo/Models/ColumnTableDataSource.swift
  iOS/Todo/Todo/Models/NewCard.swift
  iOS/Todo/Todo/ViewControllers/CardListViewController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/Views/CardListScrollView.swift
  iOS/Todo/Todo/Views/ColumnViewController's/CardCell.swift
  iOS/Todo/Todo/Views/MainViewController's/ColumnScrollView.swift
Labels: iOS, refactor

#146 [FE] 로그 기능구현 완료
  FE/src/index.html
  FE/src/style/menu.scss
  FE/src/ts/contants/constant.ts
  FE/src/ts/todoModules/eventHandles/menu.ts
  FE/src/ts/todoModules/todoView.ts
  FE/src/ts/todoModules/todoViewTemplate.ts
  FE/src/ts/utils/todoUtil.ts
Labels: FE

#151 [BE][#150] fix: Authorization 헤더 허용 옵션 추가
  BE/src/main/java/com/codesquad/team10/todo/config/CorsConfig.java
Labels: BE, bug

#154 [#153] fix: filter, interceptor에 헤더 설정
  BE/src/main/java/com/codesquad/team10/todo/config/AuthInterceptor.java
  BE/src/main/java/com/codesquad/team10/todo/config/CorsConfig.java
  BE/src/main/java/com/codesquad/team10/todo/config/MvcConfig.java
  BE/src/main/java/com/codesquad/team10/todo/config/SimpleCorsFilter.java
Labels: BE, bug

#155 Authorization 헤더 허용 배포 2
  BE/src/main/java/com/codesquad/team10/todo/config/AuthInterceptor.java
  BE/src/main/java/com/codesquad/team10/todo/config/CorsConfig.java
  BE/src/main/java/com/codesquad/team10/todo/config/MvcConfig.java
  BE/src/main/java/com/codesquad/team10/todo/config/SimpleCorsFilter.java
Labels: BE, bug, deploy

#157 [BE][#156] fix: Access-Control-Allow-Headers 의 value를 명시적으로 지정
  BE/src/main/java/com/codesquad/team10/todo/config/SimpleCorsFilter.java
Labels: BE, bug

#158 Authorization 헤더 허용 배포 3
  BE/src/main/java/com/codesquad/team10/todo/config/SimpleCorsFilter.java
Labels: BE, bug, deploy

#162 [BE][#161] fix: Access-Control-Expose-Headers 헤더로 Authorization 헤더 접근 옵션 지정
  BE/src/main/java/com/codesquad/team10/todo/config/SimpleCorsFilter.java
Labels: BE, bug

#163 Authorization 헤더 허용 배포 4
  BE/src/main/java/com/codesquad/team10/todo/config/SimpleCorsFilter.java
  FE/src/index.html
  FE/src/ts/loginModule/login.ts
  FE/src/ts/loginModule/tamplate.ts
  FE/src/ts/main.ts
  FE/src/ts/todoModules/todoController.ts
Labels: BE, bug, deploy

#164 [FE] 로그인 jwt 적용
  FE/src/ts/loginModule/data.ts
  FE/src/ts/loginModule/login.ts
  FE/src/ts/loginModules/login.ts
  FE/src/ts/loginModules/tamplate.ts
  FE/src/ts/main.ts
  FE/src/ts/todoModules/todoController.ts
  FE/src/ts/utils/httpRequestUtil.ts
Labels: FE

#165 [FE] 드래그 앤 드랍 api 적용, 로그인, 로그아웃 기능 구현
  FE/src/index.html
  FE/src/style/layout.scss
  FE/src/style/menu.scss
  FE/src/ts/contants/url.ts
  FE/src/ts/loginModules/login.ts
  FE/src/ts/loginModules/tamplate.ts
  FE/src/ts/main.ts
  FE/src/ts/todoModules/eventHandles/card.ts
  FE/src/ts/todoModules/todoController.ts
  FE/src/ts/todoModules/todoEventManager.ts
  FE/src/ts/todoModules/todoViewTemplate.ts
  FE/src/ts/utils/commonUtil.ts
  FE/src/ts/utils/httpRequestUtil.ts
Labels: FE

#169 [iOS][#92] 로그 기록 화면을 구현하였습니다.
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo/Assets.xcassets/apple.imageset/Contents.json
  iOS/Todo/Todo/Assets.xcassets/apple.imageset/apple.png
  iOS/Todo/Todo/Assets.xcassets/jason.imageset/Contents.json
  iOS/Todo/Todo/Assets.xcassets/jason.imageset/jason.jpg
  iOS/Todo/Todo/Base.lproj/Main.storyboard
  iOS/Todo/Todo/Coder/ColumnsUseCase.swift
  iOS/Todo/Todo/Coder/DeleteUseCase.swift
  iOS/Todo/Todo/Coder/EditedCardViewModelUseCase.swift
  iOS/Todo/Todo/Coder/EndPointFactory.swift
  iOS/Todo/Todo/Coder/LogUseCase.swift
  iOS/Todo/Todo/Coder/LoginUseCase.swift
  iOS/Todo/Todo/Coder/LogsUseCase.swift
  iOS/Todo/Todo/Coder/NewCardViewModelUseCase.swift
  iOS/Todo/Todo/Delegates/ContentViewDelegate.swift
  iOS/Todo/Todo/Delegates/Notification.swift
  iOS/Todo/Todo/Delegates/TitleFieldDelegate.swift
  iOS/Todo/Todo/Models/LogID.swift
  iOS/Todo/Todo/Models/LogResponse.swift
  iOS/Todo/Todo/Models/LogsResponse.swift
  iOS/Todo/Todo/Network/NetworkManager.swift
  iOS/Todo/Todo/Utils/StubJsonData.swift
  iOS/Todo/Todo/ViewControllers/AcitivitiyLogController.swift
  iOS/Todo/Todo/ViewControllers/AcitivitiyLogViewController.swift
  iOS/Todo/Todo/ViewControllers/CardViewController.swift
  iOS/Todo/Todo/ViewControllers/ColumnViewController.swift
  iOS/Todo/Todo/ViewControllers/EditingCardViewController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/ViewControllers/NewCardViewController.swift
  iOS/Todo/Todo/ViewModels/ActivityLogViewController's/LogViewModel.swift
  iOS/Todo/Todo/ViewModels/ActivityLogViewController's/LogViewModels.swift
  iOS/Todo/Todo/Views/AcitivityLogViewController's/LogCell.swift
  iOS/Todo/Todo/Views/ColumnViewController's/CardCell.swift
Labels: iOS

#171 LogService 정의하여 로그 관련 로직 처리
  BE/src/main/java/com/codesquad/team10/todo/api/CardController.java
  BE/src/main/java/com/codesquad/team10/todo/api/LogController.java
  BE/src/main/java/com/codesquad/team10/todo/config/AuthInterceptor.java
  BE/src/main/java/com/codesquad/team10/todo/constants/ExceptionMessage.java
  BE/src/main/java/com/codesquad/team10/todo/repository/CardRepository.java
  BE/src/main/java/com/codesquad/team10/todo/service/LogService.java
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo/Assets.xcassets/apple.imageset/Contents.json
  iOS/Todo/Todo/Assets.xcassets/apple.imageset/apple.png
  iOS/Todo/Todo/Assets.xcassets/jason.imageset/Contents.json
  iOS/Todo/Todo/Assets.xcassets/jason.imageset/jason.jpg
  iOS/Todo/Todo/Base.lproj/Main.storyboard
  iOS/Todo/Todo/Coder/ColumnsUseCase.swift
  iOS/Todo/Todo/Coder/DeleteUseCase.swift
  iOS/Todo/Todo/Coder/EditedCardViewModelUseCase.swift
  iOS/Todo/Todo/Coder/EndPointFactory.swift
  iOS/Todo/Todo/Coder/LogUseCase.swift
  iOS/Todo/Todo/Coder/LoginUseCase.swift
  iOS/Todo/Todo/Coder/LogsUseCase.swift
  iOS/Todo/Todo/Coder/NewCardViewModelUseCase.swift
  iOS/Todo/Todo/Delegates/ContentViewDelegate.swift
  iOS/Todo/Todo/Delegates/Notification.swift
  iOS/Todo/Todo/Delegates/TitleFieldDelegate.swift
  iOS/Todo/Todo/Models/LogID.swift
  iOS/Todo/Todo/Models/LogResponse.swift
  iOS/Todo/Todo/Models/LogsResponse.swift
  iOS/Todo/Todo/Network/NetworkManager.swift
  iOS/Todo/Todo/Utils/StubJsonData.swift
  iOS/Todo/Todo/ViewControllers/AcitivitiyLogController.swift
  iOS/Todo/Todo/ViewControllers/AcitivitiyLogViewController.swift
  iOS/Todo/Todo/ViewControllers/CardViewController.swift
  iOS/Todo/Todo/ViewControllers/ColumnViewController.swift
  iOS/Todo/Todo/ViewControllers/EditingCardViewController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/ViewControllers/NewCardViewController.swift
  iOS/Todo/Todo/ViewModels/ActivityLogViewController's/LogViewModel.swift
  iOS/Todo/Todo/ViewModels/ActivityLogViewController's/LogViewModels.swift
  iOS/Todo/Todo/Views/AcitivityLogViewController's/LogCell.swift
  iOS/Todo/Todo/Views/ColumnViewController's/CardCell.swift
Labels: BE, deploy

#172 [iOS][#170] 카드 이동 event, 카드 move to done event 를 서버 연동하였습니다.
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo/Coder/EndPointFactory.swift
  iOS/Todo/Todo/Coder/MoveUseCase.swift
  iOS/Todo/Todo/Models/ColumnTableDataSource.swift
  iOS/Todo/Todo/Models/MoveResponse.swift
  iOS/Todo/Todo/Network/NetworkManager.swift
  iOS/Todo/Todo/Utils/StubJsonData.swift
  iOS/Todo/Todo/ViewControllers/ColumnViewController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/TodoTests/DragObject.swift
Labels: enhancement, iOS, refactor

#178 [BE][#176] feat: 섹션 추가 api 구현
  BE/src/main/java/com/codesquad/team10/todo/api/SectionController.java
  BE/src/main/java/com/codesquad/team10/todo/entity/Section.java
  BE/src/main/java/com/codesquad/team10/todo/service/LogService.java
Labels: BE

#179 [BE][#176] docs: 섹션 추가 api 구현 내용 README.md에 추가
  BE/README.md
Labels: BE

#184 [FE] 컬럼 추가 기능 임시적으로 작업함
  FE/src/index.html
  FE/src/style/layout.scss
  FE/src/ts/todoModules/todoController.ts
  FE/src/ts/todoModules/todoViewTemplate.ts
Labels: FE

#185 [BE][#181] docs: 섹션 추가 api 관련 README 수정
  BE/README.md
Labels: BE

#188 [iOS][#175]컬럼 추가 기능을 구현하였습니다.
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo/Base.lproj/Main.storyboard
  iOS/Todo/Todo/Coder/ColumnUseCase.swift
  iOS/Todo/Todo/Coder/LogsUseCase.swift
  iOS/Todo/Todo/Models/LogsResponse.swift
  iOS/Todo/Todo/ViewControllers/CardViewController.swift
  iOS/Todo/Todo/ViewControllers/MainViewController.swift
  iOS/Todo/Todo/ViewControllers/NewColumnViewController.swift
  iOS/Todo/Todo/ViewModels/ActivityLogViewController's/LogViewModel.swift
Labels: enhancement, iOS
